### PR TITLE
fix #97 - failing uint on windows x86

### LINKED ISSUE #97: mir.combinatorics: uint on windows x86
seems like I should add some casts - will prepare a PR.

```
source\mir\combinatorics\package.d(129,27): Error: safe function 'mir.combinatorics.__unittestL122_2' cannot call system function 'mir.combinatorics.binomial!(BigInt, int).binomial' 
source\mir\combinatorics\package.d(700,35): Error: cannot implicitly convert expression (binomial(n, repeatLen)) of type ulong to uint
source\mir\combinatorics\package.d(983,34): Error: cannot implicitly convert expression (binomial(n + repeatLen - 1u, repeatLen)) of type ulong to uint
```

### PR DESCRIPTION
**Pull request by wilzbach**
I can't reproduce or understand this error - do you have an idea?

```
source\mir\combinatorics\package.d(129,27): Error: safe function 'mir.combinatorics.__unittestL122_2' cannot call system function 'mir.combinatorics.binomial!(BigInt, int).binomial' 
```

PR fixes the other two errors in #97, even though I think that we should use `ulong` for the `max_states` by default ...

### CODE REVIEW

File: source/mir/combinatorics/package.d [hunk 1]
```diff
@@ -697,7 +697,7 @@ public:
 
         uint repeatLen = cast(uint) state.length;
         this.n = cast(uint) n;
-        this.max_states = binomial(n, repeatLen);
+        this.max_states = cast(uint) binomial(n, repeatLen);
```
Comment (9il) [inline source/mir/combinatorics/package.d]: cast(size_t)

File: source/mir/combinatorics/package.d [hunk 2]
```diff
@@ -980,7 +980,7 @@ public:
         // set initial state and calculate max possibilities
         if (n > 0)
         {
-            max_states = binomial(n + repeatLen - 1, repeatLen);
+            max_states = cast(uint) binomial(n + repeatLen - 1, repeatLen);
```
Comment (9il) [inline source/mir/combinatorics/package.d]: ditto

**Comment by 9il** [comment]
> I can't reproduce or understand this error - do you have an idea?

Yes, on 32 bit systems bigint uses assembler version. So just remove `@safe` for unittest

**Comment by wilzbach** [comment]
> cast(size_t)

arg. Stupid mistake. sorry!

> Yes, on 32 bit systems bigint uses assembler version. So just remove @safe for unittest

Wow. Thanks!

(rebased with master)
