### PR TITLE
fix 107

### LINKED ISSUE #107: mir.las.sum: errors on linux x86_32
(see also #106)

```
dub test --arch=x86
Generating test runner configuration '__test__d_source_library__' for 'd_source_library' (sourceLibrary).
Performing "unittest" build using dmd for x86.
mir 0.13.0+commit.14.g2ab2881: building configuration "__test__d_source_library__"...
Note: Summation algorithms on x86 use 80bit representationfor single and double floating point numbers.
Note: Summation algorithms on x86 use 80bit representationfor single and double floating point numbers.
source/mir/las/sum.d(1323,25): Error: need 'this' for 's' of type 'real'
source/mir/las/sum.d(1323,29): Error: need 'this' for 'c' of type 'real'
source/mir/las/sum.d(1937,16): Error: template instance mir.las.sum.SummationAlgo!(cast(Summation)4, MapResult!(__lambda1, double[]), double) error instantiating
source/mir/las/sum.d(18,19):        instantiated from here: sum!(MapResult!(__lambda1, double[]))
source/mir/las/sum.d(2212,25): Error: undefined identifier 'note'
source/mir/las/sum.d(2212,13):        while evaluating pragma(msg, note)
source/mir/las/sum.d(387,23): Error: template instance mir.las.sum.SummationType!real error instantiating
source/mir/las/sum.d(1684,9):        instantiated from here: Summator!(real, cast(Summation)2)
source/mir/las/sum.d(2127,28):        instantiated from here: Summator!(double, cast(Summation)4)
source/mir/las/sum.d(1937,16):        instantiated from here: SummationAlgo!(cast(Summation)4, MapResult!(__lambda1, double[]), double)
source/mir/las/sum.d(18,19):        instantiated from here: sum!(MapResult!(__lambda1, double[]))
source/mir/las/sum.d(1317,30): Error: need 'this' for 'cs' of type 'real'
source/mir/las/sum.d(1317,35): Error: need 'this' for 'ccs' of type 'real'
source/mir/las/sum.d(1937,16): Error: template instance mir.las.sum.SummationAlgo!(cast(Summation)5, MapResult!(__lambda1, double[]), double) error instantiating
source/mir/las/sum.d(19,19):        instantiated from here: sum!(MapResult!(__lambda1, double[]))
source/mir/las/sum.d(1329,25): Error: need 'this' for 's' of type 'real'
source/mir/las/sum.d(1705,17): Error: 'sum -= sum2' is not a scalar, it is a Summator!(float, cast(Summation)3)
source/mir/las/sum.d(1710,30): Error: template instance mir.las.sum.Summator!(real, cast(Summation)3) error instantiating
source/mir/las/sum.d(2127,28):        instantiated from here: Summator!(double, cast(Summation)5)
source/mir/las/sum.d(1937,16):        instantiated from here: SummationAlgo!(cast(Summation)5, MapResult!(__lambda1, double[]), double)
source/mir/las/sum.d(19,19):        instantiated from here: sum!(MapResult!(__lambda1, double[]))
source/mir/las/sum.d(1329,25): Error: need 'this' for 's' of type 'real'
source/mir/las/sum.d(1705,17): Error: 'sum -= sum2' is not a scalar, it is a Summator!(double, cast(Summation)3)
source/mir/las/sum.d(1323,25): Error: need 'this' for 's' of type 'real'
dmd failed with exit code 1.
```

### PR DESCRIPTION
**Pull request by 9il**
fix #107

### CODE REVIEW

File: source/mir/las/sum.d [hunk 1]
```diff
@@ -1839,61 +1839,6 @@ nothrow unittest
...
-{
-    import std.algorithm: map;
-    import std.array: array;
-    import std.meta: AliasSeq;
-
-    alias S = Summation;
-    alias sums = AliasSeq!(S.kahan, S.pairwise, S.naive, S.fast, S.precise);
-
-    enum double M = (cast(double)2) ^^ (double.max_exp - 1);
-    Tuple!(double[], double)[] tests = [
```
Comment (9il) [inline source/mir/las/sum.d:1852]: This tests are for precise summation

Comment (wilzbach) [inline source/mir/las/sum.d:1852]: I just proposed to include them because coverage was complaining - didn't know I was breaking so much :/
